<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="2" failed="10" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-01T19:12:54 IST" name="Suite" finished-at="2021-06-01T19:19:24 IST" duration-ms="389837">
    <groups>
    </groups>
    <test started-at="2021-06-01T19:12:54 IST" name="Test" finished-at="2021-06-01T19:19:24 IST" duration-ms="389837">
      <class name="com.framework.datadriven.tests.HomeTestCSVData">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa]" started-at="2021-06-01T19:17:55 IST" name="startTest" finished-at="2021-06-01T19:17:59 IST" duration-ms="4619" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTestCSVData.signUpDataProviderTest(java.util.Map) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa]" started-at="2021-06-01T19:17:59 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="csvSignUpData" finished-at="2021-06-01T19:18:35 IST" duration-ms="35387" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{zip=560101, firstName=Javacsv, lastName=Selenium, country=world, phone=9845012345, address2=open source, city=everywhere, address1=apache, state=anywhere, email=java@selenium.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTestCSVData.signUpDataProviderTest(HomeTestCSVData.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa]" started-at="2021-06-01T19:18:35 IST" name="closeTest" finished-at="2021-06-01T19:18:36 IST" duration-ms="1044" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTestCSVData.signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa]" started-at="2021-06-01T19:18:36 IST" name="startTest" finished-at="2021-06-01T19:18:40 IST" duration-ms="4241" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTestCSVData.signUpDataProviderTest(java.util.Map) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa]" started-at="2021-06-01T19:18:40 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="csvSignUpData" finished-at="2021-06-01T19:19:16 IST" duration-ms="35727" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{zip=560101, firstName=Pythoncsv, lastName=Selenium, country=world, phone=9845012345, address2=open source, city=everywhere, address1=apache, state=anywhere, email=java@selenium.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTestCSVData.signUpDataProviderTest(HomeTestCSVData.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa]" started-at="2021-06-01T19:19:16 IST" name="closeTest" finished-at="2021-06-01T19:19:17 IST" duration-ms="1007" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTestCSVData.signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestCSVData@1e16c0aa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- com.framework.datadriven.tests.HomeTestCSVData -->
      <class name="com.framework.datadriven.tests.HomeTestExcelData">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229]" started-at="2021-06-01T19:15:11 IST" name="startTest" finished-at="2021-06-01T19:15:15 IST" duration-ms="3947" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTestExcelData.signUpDataProviderTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229]" started-at="2021-06-01T19:15:15 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="xlsSignUpData" finished-at="2021-06-01T19:15:51 IST" duration-ms="35843" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Java]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Selenium]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[java@selenium.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9845012345]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[apache]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[open source]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[everywhere]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[anywhere]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[560101]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[world]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTestExcelData.signUpDataProviderTest(HomeTestExcelData.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229]" started-at="2021-06-01T19:15:51 IST" name="closeTest" finished-at="2021-06-01T19:15:52 IST" duration-ms="1096" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTestExcelData.signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229]" started-at="2021-06-01T19:15:52 IST" name="startTest" finished-at="2021-06-01T19:15:56 IST" duration-ms="3969" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTestExcelData.signUpDataProviderTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229]" started-at="2021-06-01T19:15:56 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="xlsSignUpData" finished-at="2021-06-01T19:16:32 IST" duration-ms="35852" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Python]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Selenium]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[java@selenium.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9845012345]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[apache]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[open source]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[everywhere]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[anywhere]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[560101]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[world]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTestExcelData.signUpDataProviderTest(HomeTestExcelData.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229]" started-at="2021-06-01T19:16:32 IST" name="closeTest" finished-at="2021-06-01T19:16:33 IST" duration-ms="1006" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTestExcelData.signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelData@3b35a229] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- com.framework.datadriven.tests.HomeTestExcelData -->
      <class name="com.framework.datadriven.tests.HomeTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:12:54 IST" name="startTest" finished-at="2021-06-01T19:13:00 IST" duration-ms="5760" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTest.signInTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signInTest()[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:00 IST" name="signInTest" description="sign in test case validation" finished-at="2021-06-01T19:13:01 IST" duration-ms="1258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:01 IST" name="closeTest" finished-at="2021-06-01T19:13:02 IST" duration-ms="1399" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signInTest status=SUCCESS method=HomeTest.signInTest()[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:02 IST" name="startTest" finished-at="2021-06-01T19:13:06 IST" duration-ms="4243" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTest.signUpDataProviderTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:06 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="testData" finished-at="2021-06-01T19:13:42 IST" duration-ms="35976" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Peter]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[rama@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9845012345]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[KR Layout]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[KR Puram]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Bangalore]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Karnataka]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[560103]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[India]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTest.signUpDataProviderTest(HomeTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:42 IST" name="closeTest" finished-at="2021-06-01T19:13:44 IST" duration-ms="1073" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTest.signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:44 IST" name="startTest" finished-at="2021-06-01T19:13:48 IST" duration-ms="4285" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTest.signUpDataProviderTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:13:48 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="testData" finished-at="2021-06-01T19:14:23 IST" duration-ms="35578" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rama]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Krishna]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[rama@yahoo.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9845012786]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Patel Layout]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[IndiraNagar]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Bangalore]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Karnataka]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[561113]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[India]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTest.signUpDataProviderTest(HomeTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:14:23 IST" name="closeTest" finished-at="2021-06-01T19:14:24 IST" duration-ms="1006" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTest.signUpDataProviderTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:14:24 IST" name="startTest" finished-at="2021-06-01T19:14:28 IST" duration-ms="3946" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTest.signUpTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpTest()[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:14:28 IST" name="signUpTest" description="new user sign up test case validation without data provider" finished-at="2021-06-01T19:15:04 IST" duration-ms="35691" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUp(HomePage.java:58)
at com.framework.datadriven.tests.HomeTest.signUpTest(HomeTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:15:04 IST" name="closeTest" finished-at="2021-06-01T19:15:05 IST" duration-ms="1042" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpTest status=FAILURE method=HomeTest.signUpTest()[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:15:05 IST" name="startTest" finished-at="2021-06-01T19:15:09 IST" duration-ms="4235" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTest.validateTitle()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validateTitle()[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:15:09 IST" name="validateTitle" description="title test case validation" finished-at="2021-06-01T19:15:09 IST" duration-ms="15" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [JPetStore Demo1] but found [JPetStore Demo]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [JPetStore Demo1] but found [JPetStore Demo]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.framework.datadriven.tests.HomeTest.validateTitle(HomeTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871]" started-at="2021-06-01T19:15:09 IST" name="closeTest" finished-at="2021-06-01T19:15:10 IST" duration-ms="1151" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateTitle status=FAILURE method=HomeTest.validateTitle()[pri:0, instance:com.framework.datadriven.tests.HomeTest@700fb871] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- com.framework.datadriven.tests.HomeTest -->
      <class name="com.framework.datadriven.tests.HomeTestExcelDataMapExample">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741]" started-at="2021-06-01T19:16:33 IST" name="startTest" finished-at="2021-06-01T19:16:37 IST" duration-ms="3997" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTestExcelDataMapExample.signUpDataProviderTest(java.util.Map) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741]" started-at="2021-06-01T19:16:37 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="xlsSignUpData" finished-at="2021-06-01T19:17:12 IST" duration-ms="35771" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{zip=560101, firstName=Java, lastName=Selenium, country=world, phone=9845012345, address2=open source, city=everywhere, address1=apache, state=anywhere, email=java@selenium.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTestExcelDataMapExample.signUpDataProviderTest(HomeTestExcelDataMapExample.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741]" started-at="2021-06-01T19:17:12 IST" name="closeTest" finished-at="2021-06-01T19:17:13 IST" duration-ms="1005" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTestExcelDataMapExample.signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741]" started-at="2021-06-01T19:17:13 IST" name="startTest" finished-at="2021-06-01T19:17:18 IST" duration-ms="4435" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.HomeTestExcelDataMapExample.signUpDataProviderTest(java.util.Map) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741]" started-at="2021-06-01T19:17:18 IST" name="signUpDataProviderTest" description="Sign up test case validation with data provider" data-provider="xlsSignUpData" finished-at="2021-06-01T19:17:54 IST" duration-ms="35636" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{zip=560101, firstName=Python, lastName=Selenium, country=world, phone=9845012345, address2=open source, city=everywhere, address1=apache, state=anywhere, email=java@selenium.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to find the element using the By locator: <By.name: account.address>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to find the element using the By locator: <By.name: account.address>
at org.testng.Assert.fail(Assert.java:99)
at com.framework.datadriven.pages.BasePage.sendKeysToWebElement(BasePage.java:57)
at com.framework.datadriven.pages.HomePage.signUpDataProvider(HomePage.java:75)
at com.framework.datadriven.tests.HomeTestExcelDataMapExample.signUpDataProviderTest(HomeTestExcelDataMapExample.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpDataProviderTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741]" started-at="2021-06-01T19:17:54 IST" name="closeTest" finished-at="2021-06-01T19:17:55 IST" duration-ms="1041" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpDataProviderTest status=FAILURE method=HomeTestExcelDataMapExample.signUpDataProviderTest(java.util.Map)[pri:0, instance:com.framework.datadriven.tests.HomeTestExcelDataMapExample@9816741] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- com.framework.datadriven.tests.HomeTestExcelDataMapExample -->
      <class name="com.framework.datadriven.tests.FishTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.framework.datadriven.tests.FishTest@13d73f29]" started-at="2021-06-01T19:19:17 IST" name="startTest" finished-at="2021-06-01T19:19:22 IST" duration-ms="4892" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.datadriven.tests.FishTest.addLargeAngelFishTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="addLargeAngelFishTest()[pri:0, instance:com.framework.datadriven.tests.FishTest@13d73f29]" started-at="2021-06-01T19:19:22 IST" name="addLargeAngelFishTest" description="add large angle fish test" finished-at="2021-06-01T19:19:23 IST" duration-ms="1045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addLargeAngelFishTest -->
        <test-method is-config="true" signature="closeTest(org.testng.ITestResult)[pri:0, instance:com.framework.datadriven.tests.FishTest@13d73f29]" started-at="2021-06-01T19:19:23 IST" name="closeTest" finished-at="2021-06-01T19:19:24 IST" duration-ms="1002" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addLargeAngelFishTest status=SUCCESS method=FishTest.addLargeAngelFishTest()[pri:0, instance:com.framework.datadriven.tests.FishTest@13d73f29] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- com.framework.datadriven.tests.FishTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
